// If a person of concern has not been selected by the user, ensure the rest of
// the page is empty.
$(document).ready(function() {

    var index = document.getElementById("personofconcernselect").selectedIndex;
    if (index == 0) {
        $("#question1").hide();
        $(".personsofconcern").css("margin-bottom", "70px");
    }

    // Hide the "browse for file" and "upload file" buttons when the page is
    // loaded.
    $("#uploadButtonsSection").hide();

    // Show or hide the "browse for file" and "upload file" buttons.
    $("#showHideUpload").click(function() {
        $("#uploadButtonsSection").toggle(500);
        if ($("#showHideUpload").val() == "Add File(s)") {
            $("#showHideUpload").val("Cancel Add File(s)");
        } else {
            $("#showHideUpload").val("Add File(s)");
        }

    });

    // Add a text input box for a new Group that is impacted by an obstacle.
    $('input[name=addgroup]').on("click", function() {

        arrayIndex = $(this).attr('arrayIndex');
        divname = $(this).attr('divname');
        inputCheckBoxName = $(this).attr('inputCheckBoxName');

        cssDivName = "#" + divname;

        newGroup = "<input type='checkbox' name='" + inputCheckBoxName + "[" + arrayIndex + "]' value=':'><input class='otherGroupNames' type='text' name='" + inputCheckBoxName + "othernames[" + arrayIndex + "]' placeholder='Name of Group'>";

        $(cssDivName).append(newGroup);
    });

    $(document).on('blur', '.otherGroupNames', function() {
        var nameOfValueOfTextBox = ":" + $(this).val() + "";
        $(this).prev().val(nameOfValueOfTextBox);
    });

    // When a file is uploaded, then display the name of the file.
    $(document).on('change', 'input[name=browseButton]', function() {
        $('input[name = "natlinstrurefupload"]').val($(this).val());
    });

    $(document).on('mousedown', 'button[name=uploadButton]', function() {

        $('p[id="uploadsuccess"]').text('Please wait. File upload in progress.');

    });

    // Upload the documents generated by the consultations with persons of
    // concern.
    $(document).on('mouseup', 'button[name=uploadButton]', function() {

        // $('p[id="uploadsuccess"]').text('File uploading. Please wait.');

        var fileToUpload = new FormData();
        fileToUpload.append('file', $('input[name="browseButton"]')[0].files[0]);

        $.ajax({
        url : 'UploadController',
        type : 'POST',
        async : false,
        cache : false,
        processData : false,
        contentType : false,
        data : fileToUpload,
        success : function(responseText) {
            uploadResp(responseText);

        },
        error : function(responseText) {
            uploadRespError(responseText);
        }
        });
    });

});

// When I file is successfully uploaded, display it on the page.
function uploadResp(responseText) {

    var fileStorageName = responseText.match(/\d{2}\.\d{2}\.\d{2}.*/);
    var fileURL = responseText;
    var fileDisplayName = responseText.split(/\d{2}\.\d{2}\.\d{2}_/);
    var newDocLinkHtml = "";
    var noOfDocs = 0;

    fileStorageName = String(fileStorageName).replace(/[^\x00-\x7F]/g, "");
    fileURL = String(fileURL).replace(/[^\x00-\x7F]/g, "");

    // Indicate the file was successfully uploaded.
    $('p[id="uploadsuccess"]').text('The file has been successfully uploaded! To ensure your changes are saved click the "Save Changes" button. ');

    $('.browsefile').contents().last().replaceWith("Click to Browse for Another File");

    // Find out how many files are already displayed on the page.
    $("input[name^='docStorageName']").each(function() {
        noOfDocs = noOfDocs + 1;
    });

    // For the file that was just uploaded, added it to the page as hidden
    // input.

    newDocLinkHtml = newDocLinkHtml + "<a class='docVisibleLink' href='" + fileURL + "'>" + fileDisplayName[1] + "</a> <br><br>";
    newDocLinkHtml = newDocLinkHtml + "<input type='hidden' name='docStorageName[" + noOfDocs + "]' value='" + fileStorageName + "'>";
    newDocLinkHtml = newDocLinkHtml + "<input type='hidden' name='docDisplayName[" + noOfDocs + "]' value='" + fileDisplayName[1] + "'>";
    newDocLinkHtml = newDocLinkHtml + "<input type='hidden' name='docURL[" + noOfDocs + "]' value='" + fileURL + "'>";

    lastDocInList = noOfDocs - 1;

    $("#showHideUpload").before(newDocLinkHtml);

}
// If the uploading of the file fails, display it on the page.
function uploadRespError(responseText) {

    $('p[id="uploadsuccess"]').text('Uploading of file failed.');
}
// Expand all instrument tables.
function expandAll() {
    $(".tablebody").show();
}

// Collapse all instrument tables.
function collapseAll() {
    $(".tablebody").hide();
}

// Expand a single obstacle table.
function toggletablebody(table) {
    $("#" + table + " tbody").toggle();
}
